<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DTOO\**" />
    <Compile Remove="Fachaada\**" />
    <Compile Remove="NewFolder\**" />
    <EmbeddedResource Remove="DTOO\**" />
    <EmbeddedResource Remove="Fachaada\**" />
    <EmbeddedResource Remove="NewFolder\**" />
    <None Remove="DTOO\**" />
    <None Remove="Fachaada\**" />
    <None Remove="NewFolder\**" />
  </ItemGroup>

</Project>
